// flow-typed signature: d00954ffc51fb2168533b342fcfc98be
// flow-typed version: <<STUB>>/jest-leak-detector_v~24.7.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-leak-detector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-leak-detector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-leak-detector/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-leak-detector/build/index.js' {
  declare module.exports: $Exports<'jest-leak-detector/build/index'>;
}
